[tool.isort]
skip_glob = ["turing/*"]
line_length = 120

[tool.mypy]
exclude = ["turing/"]
check_untyped_defs = true
disallow_any_unimported = true
disallow_untyped_defs = true
no_implicit_optional = true
pretty = true
show_error_codes = true
strict = true
warn_return_any = true
warn_unused_ignores = true

[tool.pytest.ini_options]

[tool.ruff]
exclude = ["turing/"]
line-length = 120
target-version = "py311"
select = ["ANN", "D", "E", "F", "FLY", "ICN", "N", "Q", "RUF", "UP", "W"]

[tool.ruff.pycodestyle]
max-doc-length = 120

[tool.ruff.pydocstyle]
convention = "numpy"
